test

diff --git a/frontend/Dockerfile b/frontend/Dockerfile
--- a/frontend/Dockerfile
+++ b/frontend/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:24 AS build
+FROM node:24
 
 ARG REACT_APP_API_URL=http://localhost:8000
 
@@ -7,7 +7,9 @@ COPY . /app
 
 RUN echo "REACT_APP_API_URL=${REACT_APP_API_URL}" > .env
 
-RUN npm install --force && \
-    npm run build
+RUN npm install --force
+
+# Debug: list node_modules/react-scripts
+RUN ls -l node_modules/react-scripts || echo "react-scripts not found"
 
 CMD ["npm", "start", "--", "--host", "0.0.0.0"]
